export const products = [
       {
         id: 1,
         title: "Samsung S21",
         description: "black in color",
         price: "2500",
         img: "./images/image1.jpg",
         quantity: 1,
       },
       {
         id: 2,
         title: "Nokia T21",
         description: "white in color",
         price: "2300",
         img: "./images/image2.jpg",
         quantity: 1,
       },
       {
         id: 3,
         title: "Redmi 9",
         description: "black in color",
         price: "3500",
         img: "https://images-na.ssl-images-amazon.com/images/I/71A9Vo1BatL._SL1500_.jpg",
         quantity: 1,
       },
       {
         id: 4,
         title: "Iphone 12",
         description: "Purple in color",
         price: "90500",
         img: "https://images-na.ssl-images-amazon.com/images/I/71hIfcIPyxS._SL1500_.jpg",
         quantity: 1,
       },
       {
         id: 5,
         title: "Infinix Note 11",
         description: "Grey in color",
         price: "2500",
         img: "./images/image3.jfif",
         quantity: 1,
       },
       {
         id: 6,
         title: "OPPO F21 Pro",
         description: "yello in color",
         price: "3500",
         img: "./images/image4.jpg",
         quantity: 1,
       },
       {
         id: 7,
         title: "Tecno Spark 8",
         description: "black in color",
         price: "2500",
         img: "./images/image5.jpg",
         quantity: 1,
       },
       {
         id: 8,
         title: "Iphone 12 Pro",
         description: "Black in color",
         price: "90500",
         img: "./images/image6.jpg",
         quantity: 1,
       },
       {
         id: 9,
         title: "Samsung a51",
         description: "black in color",
         price: "2500",
         img: "./images/image7.jpg",
         quantity: 1,
       },
     ];